### ISSUE TITLE
Version 4.00 correctly packaged for MiKTeX?

### ISSUE THREAD

**Issue by elenziat** [tudace/tuda_latex_templates#499]
After updating to version 4.00 over the MiKTeX Console, I couldn't compile a document using the tudabeamer-class any more getting the error "tudabeamer.cls" not found. (I didn't test the other classes.)

In the installation location there were only some dtx and one ins file. 

(And even after calling latex with the ins file myself, the compilation doesn't work, although the cls-files are present now. Especially the latter seems weird to me, but I didn't investigate later but reset my MiKTeX directory to the state before the update.)

**Comment by TeXhackse** [comment]
Thanks for reporting. Well… it's packaged correctly for CTAN but seems like MikTeX is not automatically working with the change to dtx. I am a bit surprised they already included the update. Usually that takes longer. 

In that case it will not work for the other classes as well. I will try to get them to fix it. Sadly I cannot do anything about it myself. But what would work as a workaround is copying the files locally or use the l3build script out of this repository.

**Comment by TeXhackse** [comment]
I just found out hat there is something I could do about it. I will try to prepare a pull request for miktex-packaging on that. Needs some testing. Actually the issue rather is, that they required some modification for the old setup so probably that's why the other part is not working.

https://github.com/MiKTeX/miktex-packaging/blob/master/tdsutil/recipes/tuda-ci.ini is the thing that needs a change.

**Comment by TeXhackse** [comment]
As there were some support requests via the ULB and I don't know when my Pull Request for MikTeX will be merged… 

There is a tds archive in the Release https://github.com/tudace/tuda_latex_templates/releases/tag/v4.00 You can unpack that instead of using l3build and copy the package and class files to your working director (or install those manually). 

The files are within tex/latex/tuda-ci subdirectory of the tds achive.

**Comment by FlixXIV** [comment]
Hey it seems whether the problem still exists. I get the error message "tudaexercise.cls not found" for example. If I copy the unzipped tuda-ci.tds archive into my working directory, it still doesn't work. I think it needs a link anyhow but I don't know how to do that.

**Comment by FlixXIV** [comment]
> As there were some support requests via the ULB and I don't know when my Pull Request for MikTeX will be merged…
> 
> There is a tds archive in the Release https://github.com/tudace/tuda_latex_templates/releases/tag/v4.00 You can unpack that instead of using l3build and copy the package and class files to your working director (or install those manually).
> 
> The files are within tex/latex/tuda-ci subdirectory of the tds achive.

Hey it seems whether the problem still exists. I get the error message "tudaexercise.cls not found" for example. 

If I add the files to the workspace, it works. However, it is a bit confusing. If I then combine the files in a folder, which is also in the workspace, it no longer works. Is there a way to refer to the files in a subordinate folder? Thanks in advance

**Comment by FlixXIV** [comment]
thx

**Comment by FlixXIV** [comment]
Hey, 

i've included the files, given in the tds repository via Miktex. Now it works, but Citing does not. I use biblatex and include my own library, but if i write \cite{totaleDiffbarkteit} the pdf produced gives

![Image](https://github.com/user-attachments/assets/1b6c7293-7ad1-4df4-80b2-ba1e3ac81100)

**Comment by FlixXIV** [comment]
Yes you're right. I forgot to adjust my editor, thx for your help and the tips

**Comment by TeXhackse** [comment]
Mein Pull Request has been merged this morning. So I would guess it should be resolved. In case someone of you who has an installed could test it, that would be helpful, otherwhise I will do it myself but probably will not manage to find time before the weekend.

**Comment by TeXhackse** [comment]
Might be, that there has to be an update on the server first, as https://miktex.org/packages/tuda-ci/files still lists them wrong. But that's just a guess.

**Comment by elenziat** [comment]
> My Pull Request has been merged this morning. So I would guess it should be resolved. In case someone of you who has an installed could test it, that would be helpful, otherwise I will do it myself but probably will not manage to find time before the weekend.

updating over miktex works now, thanks!

**Comment by as2-0** [comment]
I still get: "File `tudathesis.cfg' not found."
According to MikTeX the package was packed "Wed Mar 5 10:56:39 2025".

**Comment by TeXhackse** [comment]
Thanks … I see … for me that means miktex-packaging moves some files before unpacking the docstrip… which is … weird… I try to find a solution So long you have to keep the file within the working directory …

**Comment by Ticqi** [comment]
If I didn't miss anything the file 'tudathesis.cfg' isn't part of the package (or the git repo) anymore since the update to 4.0, so it's not surprising that it's not found. I had to go back to an earlier stage of the repo to find the file.

**Comment by TeXhackse** [comment]
It is part of the package it's generated the same way as the sty files are. l3build is taking care of that process. And it's also part of the TeX Live release which manages to handle this in a better way. 

In case you don't want to use l3build you can always use the TDS-archives  which included the unpacked files, e.g https://github.com/tudace/tuda_latex_templates/releases/download/v4.01/tuda-ci_v4.01.tds.zip

Please do not use an old version of the file as there have been changes and you should not mix it up.

**Comment by TeXhackse** [comment]
This should now finally be resolved.
