### ISSUE TITLE
Outdated version: Name in \affidavit does not appear

### ISSUE THREAD

**Issue by speedlatex** [tudace/tuda_latex_templates#86]
I´m writing my Bachelorthesis with the new TU-Design, but my name does not appear in the first sentence of affidavit. Isn´t it supposed to be automatically there, when I write my name in the "author"-brackets?

Best regards,
Timo

**Comment by TeXhackse** [comment]
You used `\author{Name}`? Are you sure you did use the current Version. We had a bug about that some time ago, but is has been fixed since some releases already.

**Comment by speedlatex** [comment]
Yes, I'm using \author{Name}.
 Maybe I don't have the latest version. Should I download everything again from: https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.de.jsp or is there another way to get the updates?

**Comment by schoeps** [comment]
Did you install the templates manually in the first place? If you use miktex or texlive then you just need to update them (e.g `tlmgr update`). You should be able to find which version you are using by looking at the log files!

**Comment by TeXhackse** [comment]
I sadly cant check if everything on that homepage is currently up to date, since I am an extern. But I think it's a problem of an outdated version, since we can't reconstruct it. We can ensure that, if you show us a log file.

**Comment by schoeps** [comment]
@TeXhackse I can confirm that the zip-file at https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.en.jsp is up to date (2.01) @marklaz is on his toes :)

**Comment by speedlatex** [comment]
I´'m using MikTeX and I updated it a few minutes ago, but now, I am not able to comoile my file any more. I guess a *.sty file is missing, because I get the error:
! LaTeX Error: File `ifxetex.sty' not found.

Its in line 6 of roboto.sty

**Comment by schoeps** [comment]
> I'm using MikTeX and I updated it a few minutes ago, but now, I am not able to compile my file any more. I guess a *.sty file is missing, because I get the error:
> ! LaTeX Error: File `ifxetex.sty' not found.

I am no miktex expert but it seems you are missing the package [ifxetex](https://www.ctan.org/pkg/ifxetex), so you could go to the Miktex package manager and install it manually?

**Comment by TeXhackse** [comment]
yup thats possible + if he has autoinstall enabled his will just need several runs up to a succeeding one.

**Comment by speedlatex** [comment]
I never installed a package manually. Your link to ifxetex says, that ifxetex is part of iftex. And I have iftex in my list of packages in MikTeX. But somehow the 'ifxetex.sty'- File is missing. 
So I downloaded ifxetex from your Link https://www.ctan.org/pkg/ifxetex and unpacked the *zip somewhere. I know that this forum is not made for such problems, but do you know in which folder I have to put the ifxetex.sty'- File?

**Comment by schoeps** [comment]
> but do you know in which folder I have to put the ifxetex.sty'- File?

It should work if you put the file in the same folder as your main tex file but this is an ugly hack. Nonetheless, it may allow you to work during the weekend... you need to promise that you do it properly next week! :) maybe ask a colleague?

**Comment by speedlatex** [comment]
Okay, I copied everything in the same folder in whcih my tex file is. Than it worked an I could compile. But my origin problem, that my name does not appear in the \affidavit remains.

**Comment by speedlatex** [comment]
First two lines of the log File: This is LuaTeX, Version 1.11.2 (MiKTeX 2.9.7250 64-bit)  (format=lualatex 2019.11.15)  15 NOV 2019 19:41
 restricted system commands enabled.

**Comment by schoeps** [comment]
This is not enough info (these version numbers are about latex itself). You can upload the full log, e.g. at https://gist.github.com and paste the url here....

**Comment by speedlatex** [comment]
Here: https://gist.github.com/speedlatex/f8d939797cf2d9342fb98ba4e7bd1c6f

**Comment by schoeps** [comment]
You ate still using the old version. There is a line line that:

> Document Class: tudapub 2019/08/05 v1.01

Can you double check that really updated all Miktex packages? This could also explain your issue with `iftex`. There may be an incomplete update.

**Comment by speedlatex** [comment]
I realized it a few minutes ago and updated it now erverything in the right way. But still, it doesnt work. A friend of mine is helping me now.

**Comment by schoeps** [comment]
Another ugly work around is putting the contents of the tex-folder from the zip https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.en.jsp in your current directory..... but this all should be fixed by a proper update!

**Comment by speedlatex** [comment]
Finally I was able to make it all work: 

I had to delete ifxetex from the generic folder of MikTeX. Furthermore I installed iftex as Admin AND User, which caused further problems. Afer fixing this it worked. Nevertheless, I still get the message: "Unfortunately, the package iftex could not be installed. Please check the log file. " , but I can compile and get a PDF Output.

**Comment by TeXhackse** [comment]
Maybe you should “check the log file”?

**Comment by schoeps** [comment]
Another final suggestion: just uninstall Miktex and reinstall. If you have enough disk space then consider a full installation using the "net installer" (https://miktex.org/download). This issue is not about our templates, so I will close it.
